<?php

use Illuminate\Database\Seeder;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();
	$countries = array(
		array("id" => 1, "code" => "AF", "name" => "Afghanistan", "phonecode" => 93, "currency_name" => "Afghan afghani", "currency_symbol" => "", "currency_code" => "AFN"),
		array("id" => 2, "code" => "AL", "name" => "Albania", "phonecode" => 355, "currency_name" => "Albanian lek", "currency_symbol" => "", "currency_code" => "ALL"),
		array("id" => 3, "code" => "DZ", "name" => "Algeria", "phonecode" => 213, "currency_name" => "Algerian dinar", "currency_symbol" => "", "currency_code" => "DZD"),
		array("id" => 4, "code" => "AS", "name" => "American Samoa", "phonecode" => 1684, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 5, "code" => "AD", "name" => "Andorra", "phonecode" => 376, "currency_name" => "Euro", "currency_symbol" => "", "currency_code" => "EUR"),
		array("id" => 6, "code" => "AO", "name" => "Angola", "phonecode" => 244, "currency_name" => "Angolan kwanza", "currency_symbol" => "", "currency_code" => "AOA"),
		array("id" => 7, "code" => "AI", "name" => "Anguilla", "phonecode" => 1264, "currency_name" => "East Caribbean dolla", "currency_symbol" => "", "currency_code" => "XCD"),
		array("id" => 8, "code" => "AQ", "name" => "Antarctica", "phonecode" => 0, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 9, "code" => "AG", "name" => "Antigua And Barbuda", "phonecode" => 1268, "currency_name" => "East Caribbean dolla", "currency_symbol" => "", "currency_code" => "XCD"),
		array("id" => 10, "code" => "AR", "name" => "Argentina", "phonecode" => 54, "currency_name" => "Argentine peso", "currency_symbol" => "", "currency_code" => "ARS"),
		array("id" => 11, "code" => "AM", "name" => "Armenia", "phonecode" => 374, "currency_name" => "Armenian dram", "currency_symbol" => "", "currency_code" => "AMD"),
		array("id" => 12, "code" => "AW", "name" => "Aruba", "phonecode" => 297, "currency_name" => "Aruban florin", "currency_symbol" => "", "currency_code" => "AWG"),
		array("id" => 13, "code" => "AU", "name" => "Australia", "phonecode" => 61, "currency_name" => "Australian dollar", "currency_symbol" => "", "currency_code" => "AUD"),
		array("id" => 14, "code" => "AT", "name" => "Austria", "phonecode" => 43, "currency_name" => "Euro", "currency_symbol" => "", "currency_code" => "EUR"),
		array("id" => 15, "code" => "AZ", "name" => "Azerbaijan", "phonecode" => 994, "currency_name" => "Azerbaijani manat", "currency_symbol" => "", "currency_code" => "AZN"),
		array("id" => 16, "code" => "BS", "name" => "Bahamas The", "phonecode" => 1242, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 17, "code" => "BH", "name" => "Bahrain", "phonecode" => 973, "currency_name" => "Bahraini dinar", "currency_symbol" => "", "currency_code" => "BHD"),
		array("id" => 18, "code" => "BD", "name" => "Bangladesh", "phonecode" => 880, "currency_name" => "Bangladeshi taka", "currency_symbol" => "", "currency_code" => "BDT"),
		array("id" => 19, "code" => "BB", "name" => "Barbados", "phonecode" => 1246, "currency_name" => "Barbadian dollar", "currency_symbol" => "", "currency_code" => "BBD"),
		array("id" => 20, "code" => "BY", "name" => "Belarus", "phonecode" => 375, "currency_name" => "Belarusian ruble", "currency_symbol" => "", "currency_code" => "BYR"),
		array("id" => 21, "code" => "BE", "name" => "Belgium", "phonecode" => 32, "currency_name" => "Euro", "currency_symbol" => "", "currency_code" => "EUR"),
		array("id" => 22, "code" => "BZ", "name" => "Belize", "phonecode" => 501, "currency_name" => "Belize dollar", "currency_symbol" => "", "currency_code" => "BZD"),
		array("id" => 23, "code" => "BJ", "name" => "Benin", "phonecode" => 229, "currency_name" => "West African CFA fra", "currency_symbol" => "", "currency_code" => "XOF"),
		array("id" => 24, "code" => "BM", "name" => "Bermuda", "phonecode" => 1441, "currency_name" => "Bermudian dollar", "currency_symbol" => "", "currency_code" => "BMD"),
		array("id" => 25, "code" => "BT", "name" => "Bhutan", "phonecode" => 975, "currency_name" => "Bhutanese ngultrum", "currency_symbol" => "", "currency_code" => "BTN"),
		array("id" => 26, "code" => "BO", "name" => "Bolivia", "phonecode" => 591, "currency_name" => "Bolivian boliviano", "currency_symbol" => "", "currency_code" => "BOB"),
		array("id" => 27, "code" => "BA", "name" => "Bosnia and Herzegovina", "phonecode" => 387, "currency_name" => "Bosnia and Herzegovi", "currency_symbol" => "", "currency_code" => "BAM"),
		array("id" => 28, "code" => "BW", "name" => "Botswana", "phonecode" => 267, "currency_name" => "Botswana pula", "currency_symbol" => "", "currency_code" => "BWP"),
		array("id" => 29, "code" => "BV", "name" => "Bouvet Island", "phonecode" => 0, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 30, "code" => "BR", "name" => "Brazil", "phonecode" => 55, "currency_name" => "Brazilian real", "currency_symbol" => "", "currency_code" => "BRL"),
		array("id" => 31, "code" => "IO", "name" => "British Indian Ocean Territory", "phonecode" => 246, "currency_name" => "United States dollar", "currency_symbol" => "", "currency_code" => "USD"),
		array("id" => 32, "code" => "BN", "name" => "Brunei", "phonecode" => 673, "currency_name" => "Brunei dollar", "currency_symbol" => "", "currency_code" => "BND"),
		array("id" => 33, "code" => "BG", "name" => "Bulgaria", "phonecode" => 359, "currency_name" => "Bulgarian lev", "currency_symbol" => "", "currency_code" => "BGN"),
		array("id" => 34, "code" => "BF", "name" => "Burkina Faso", "phonecode" => 226, "currency_name" => "West African CFA fra", "currency_symbol" => "", "currency_code" => "XOF"),
		array("id" => 35, "code" => "BI", "name" => "Burundi", "phonecode" => 257, "currency_name" => "Burundian franc", "currency_symbol" => "", "currency_code" => "BIF"),
		array("id" => 36, "code" => "KH", "name" => "Cambodia", "phonecode" => 855, "currency_name" => "Cambodian riel", "currency_symbol" => "", "currency_code" => "KHR"),
		array("id" => 37, "code" => "CM", "name" => "Cameroon", "phonecode" => 237, "currency_name" => "Central African CFA ", "currency_symbol" => "", "currency_code" => "XAF"),
		array("id" => 38, "code" => "CA", "name" => "Canada", "phonecode" => 1, "currency_name" => "Canadian dollar", "currency_symbol" => "", "currency_code" => "CAD"),
		array("id" => 39, "code" => "CV", "name" => "Cape Verde", "phonecode" => 238, "currency_name" => "Cape Verdean escudo", "currency_symbol" => "", "currency_code" => "CVE"),
		array("id" => 40, "code" => "KY", "name" => "Cayman Islands", "phonecode" => 1345, "currency_name" => "Cayman Islands dolla", "currency_symbol" => "", "currency_code" => "KYD"),
		array("id" => 41, "code" => "CF", "name" => "Central African Republic", "phonecode" => 236, "currency_name" => "Central African CFA ", "currency_symbol" => "", "currency_code" => "XAF"),
		array("id" => 42, "code" => "TD", "name" => "Chad", "phonecode" => 235, "currency_name" => "Central African CFA ", "currency_symbol" => "", "currency_code" => "XAF"),
		array("id" => 43, "code" => "CL", "name" => "Chile", "phonecode" => 56, "currency_name" => "Chilean peso", "currency_symbol" => "", "currency_code" => "CLP"),
		array("id" => 44, "code" => "CN", "name" => "China", "phonecode" => 86, "currency_name" => "Chinese yuan", "currency_symbol" => "", "currency_code" => "CNY"),
		array("id" => 45, "code" => "CX", "name" => "Christmas Island", "phonecode" => 61, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 46, "code" => "CC", "name" => "Cocos (Keeling) Islands", "phonecode" => 672, "currency_name" => "Australian dollar", "currency_symbol" => "", "currency_code" => "AUD"),
		array("id" => 47, "code" => "CO", "name" => "Colombia", "phonecode" => 57, "currency_name" => "Colombian peso", "currency_symbol" => "", "currency_code" => "COP"),
		array("id" => 48, "code" => "KM", "name" => "Comoros", "phonecode" => 269, "currency_name" => "Comorian franc", "currency_symbol" => "", "currency_code" => "KMF"),
		array("id" => 49, "code" => "CG", "name" => "Congo", "phonecode" => 242, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 50, "code" => "CD", "name" => "Congo The Democratic Republic Of The", "phonecode" => 242, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 51, "code" => "CK", "name" => "Cook Islands", "phonecode" => 682, "currency_name" => "New Zealand dollar", "currency_symbol" => "", "currency_code" => "NZD"),
		array("id" => 52, "code" => "CR", "name" => "Costa Rica", "phonecode" => 506, "currency_name" => "Costa Rican colón", "currency_symbol" => "", "currency_code" => "CRC"),
		array("id" => 53, "code" => "CI", "name" => "Cote D'Ivoire (Ivory Coast)", "phonecode" => 225, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 54, "code" => "HR", "name" => "Croatia (Hrvatska)", "phonecode" => 385, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 55, "code" => "CU", "name" => "Cuba", "phonecode" => 53, "currency_name" => "Cuban convertible pe", "currency_symbol" => "", "currency_code" => "CUC"),
		array("id" => 56, "code" => "CY", "name" => "Cyprus", "phonecode" => 357, "currency_name" => "Euro", "currency_symbol" => "", "currency_code" => "EUR"),
		array("id" => 57, "code" => "CZ", "name" => "Czech Republic", "phonecode" => 420, "currency_name" => "Czech koruna", "currency_symbol" => "", "currency_code" => "CZK"),
		array("id" => 58, "code" => "DK", "name" => "Denmark", "phonecode" => 45, "currency_name" => "Danish krone", "currency_symbol" => "", "currency_code" => "DKK"),
		array("id" => 59, "code" => "DJ", "name" => "Djibouti", "phonecode" => 253, "currency_name" => "Djiboutian franc", "currency_symbol" => "", "currency_code" => "DJF"),
		array("id" => 60, "code" => "DM", "name" => "Dominica", "phonecode" => 1767, "currency_name" => "East Caribbean dolla", "currency_symbol" => "", "currency_code" => "XCD"),
		array("id" => 61, "code" => "DO", "name" => "Dominican Republic", "phonecode" => 1809, "currency_name" => "Dominican peso", "currency_symbol" => "", "currency_code" => "DOP"),
		array("id" => 62, "code" => "TP", "name" => "East Timor", "phonecode" => 670, "currency_name" => "United States dollar", "currency_symbol" => "", "currency_code" => "USD"),
		array("id" => 63, "code" => "EC", "name" => "Ecuador", "phonecode" => 593, "currency_name" => "United States dollar", "currency_symbol" => "", "currency_code" => "USD"),
		array("id" => 64, "code" => "EG", "name" => "Egypt", "phonecode" => 20, "currency_name" => "Egyptian pound", "currency_symbol" => "", "currency_code" => "EGP"),
		array("id" => 65, "code" => "SV", "name" => "El Salvador", "phonecode" => 503, "currency_name" => "United States dollar", "currency_symbol" => "", "currency_code" => "USD"),
		array("id" => 66, "code" => "GQ", "name" => "Equatorial Guinea", "phonecode" => 240, "currency_name" => "Central African CFA ", "currency_symbol" => "", "currency_code" => "XAF"),
		array("id" => 67, "code" => "ER", "name" => "Eritrea", "phonecode" => 291, "currency_name" => "Eritrean nakfa", "currency_symbol" => "", "currency_code" => "ERN"),
		array("id" => 68, "code" => "EE", "name" => "Estonia", "phonecode" => 372, "currency_name" => "Euro", "currency_symbol" => "", "currency_code" => "EUR"),
		array("id" => 69, "code" => "ET", "name" => "Ethiopia", "phonecode" => 251, "currency_name" => "Ethiopian birr", "currency_symbol" => "", "currency_code" => "ETB"),
		array("id" => 70, "code" => "XA", "name" => "External Territories of Australia", "phonecode" => 61, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 71, "code" => "FK", "name" => "Falkland Islands", "phonecode" => 500, "currency_name" => "Falkland Islands pou", "currency_symbol" => "", "currency_code" => "FKP"),
		array("id" => 72, "code" => "FO", "name" => "Faroe Islands", "phonecode" => 298, "currency_name" => "Danish krone", "currency_symbol" => "", "currency_code" => "DKK"),
		array("id" => 73, "code" => "FJ", "name" => "Fiji Islands", "phonecode" => 679, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 74, "code" => "FI", "name" => "Finland", "phonecode" => 358, "currency_name" => "Euro", "currency_symbol" => "", "currency_code" => "EUR"),
		array("id" => 75, "code" => "FR", "name" => "France", "phonecode" => 33, "currency_name" => "Euro", "currency_symbol" => "", "currency_code" => "EUR"),
		array("id" => 76, "code" => "GF", "name" => "French Guiana", "phonecode" => 594, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 77, "code" => "PF", "name" => "French Polynesia", "phonecode" => 689, "currency_name" => "CFP franc", "currency_symbol" => "", "currency_code" => "XPF"),
		array("id" => 78, "code" => "TF", "name" => "French Southern Territories", "phonecode" => 0, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 79, "code" => "GA", "name" => "Gabon", "phonecode" => 241, "currency_name" => "Central African CFA ", "currency_symbol" => "", "currency_code" => "XAF"),
		array("id" => 80, "code" => "GM", "name" => "Gambia The", "phonecode" => 220, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 81, "code" => "GE", "name" => "Georgia", "phonecode" => 995, "currency_name" => "Georgian lari", "currency_symbol" => "", "currency_code" => "GEL"),
		array("id" => 82, "code" => "DE", "name" => "Germany", "phonecode" => 49, "currency_name" => "Euro", "currency_symbol" => "", "currency_code" => "EUR"),
		array("id" => 83, "code" => "GH", "name" => "Ghana", "phonecode" => 233, "currency_name" => "Ghana cedi", "currency_symbol" => "", "currency_code" => "GHS"),
		array("id" => 84, "code" => "GI", "name" => "Gibraltar", "phonecode" => 350, "currency_name" => "Gibraltar pound", "currency_symbol" => "", "currency_code" => "GIP"),
		array("id" => 85, "code" => "GR", "name" => "Greece", "phonecode" => 30, "currency_name" => "Euro", "currency_symbol" => "", "currency_code" => "EUR"),
		array("id" => 86, "code" => "GL", "name" => "Greenland", "phonecode" => 299, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 87, "code" => "GD", "name" => "Grenada", "phonecode" => 1473, "currency_name" => "East Caribbean dolla", "currency_symbol" => "", "currency_code" => "XCD"),
		array("id" => 88, "code" => "GP", "name" => "Guadeloupe", "phonecode" => 590, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 89, "code" => "GU", "name" => "Guam", "phonecode" => 1671, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 90, "code" => "GT", "name" => "Guatemala", "phonecode" => 502, "currency_name" => "Guatemalan quetzal", "currency_symbol" => "", "currency_code" => "GTQ"),
		array("id" => 91, "code" => "XU", "name" => "Guernsey and Alderney", "phonecode" => 44, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 92, "code" => "GN", "name" => "Guinea", "phonecode" => 224, "currency_name" => "Guinean franc", "currency_symbol" => "", "currency_code" => "GNF"),
		array("id" => 93, "code" => "GW", "name" => "Guinea-Bissau", "phonecode" => 245, "currency_name" => "West African CFA fra", "currency_symbol" => "", "currency_code" => "XOF"),
		array("id" => 94, "code" => "GY", "name" => "Guyana", "phonecode" => 592, "currency_name" => "Guyanese dollar", "currency_symbol" => "", "currency_code" => "GYD"),
		array("id" => 95, "code" => "HT", "name" => "Haiti", "phonecode" => 509, "currency_name" => "Haitian gourde", "currency_symbol" => "", "currency_code" => "HTG"),
		array("id" => 96, "code" => "HM", "name" => "Heard and McDonald Islands", "phonecode" => 0, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 97, "code" => "HN", "name" => "Honduras", "phonecode" => 504, "currency_name" => "Honduran lempira", "currency_symbol" => "", "currency_code" => "HNL"),
		array("id" => 98, "code" => "HK", "name" => "Hong Kong S.A.R.", "phonecode" => 852, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 99, "code" => "HU", "name" => "Hungary", "phonecode" => 36, "currency_name" => "Hungarian forint", "currency_symbol" => "", "currency_code" => "HUF"),
		array("id" => 100, "code" => "IS", "name" => "Iceland", "phonecode" => 354, "currency_name" => "Icelandic króna", "currency_symbol" => "", "currency_code" => "ISK"),
		array("id" => 101, "code" => "IN", "name" => "India", "phonecode" => 91, "currency_name" => "Indian rupee", "currency_symbol" => "₹", "currency_code" => "INR"),
		array("id" => 102, "code" => "id", "name" => "Indonesia", "phonecode" => 62, "currency_name" => "Indonesian rupiah", "currency_symbol" => "", "currency_code" => "IDR"),
		array("id" => 103, "code" => "IR", "name" => "Iran", "phonecode" => 98, "currency_name" => "Iranian rial", "currency_symbol" => "", "currency_code" => "IRR"),
		array("id" => 104, "code" => "IQ", "name" => "Iraq", "phonecode" => 964, "currency_name" => "Iraqi dinar", "currency_symbol" => "", "currency_code" => "IQD"),
		array("id" => 105, "code" => "IE", "name" => "Ireland", "phonecode" => 353, "currency_name" => "Euro", "currency_symbol" => "", "currency_code" => "EUR"),
		array("id" => 106, "code" => "IL", "name" => "Israel", "phonecode" => 972, "currency_name" => "Israeli new shekel", "currency_symbol" => "", "currency_code" => "ILS"),
		array("id" => 107, "code" => "IT", "name" => "Italy", "phonecode" => 39, "currency_name" => "Euro", "currency_symbol" => "", "currency_code" => "EUR"),
		array("id" => 108, "code" => "JM", "name" => "Jamaica", "phonecode" => 1876, "currency_name" => "Jamaican dollar", "currency_symbol" => "", "currency_code" => "JMD"),
		array("id" => 109, "code" => "JP", "name" => "Japan", "phonecode" => 81, "currency_name" => "Japanese yen", "currency_symbol" => "", "currency_code" => "JPY"),
		array("id" => 110, "code" => "XJ", "name" => "Jersey", "phonecode" => 44, "currency_name" => "British pound", "currency_symbol" => "", "currency_code" => "GBP"),
		array("id" => 111, "code" => "JO", "name" => "Jordan", "phonecode" => 962, "currency_name" => "Jordanian dinar", "currency_symbol" => "", "currency_code" => "JOD"),
		array("id" => 112, "code" => "KZ", "name" => "Kazakhstan", "phonecode" => 7, "currency_name" => "Kazakhstani tenge", "currency_symbol" => "", "currency_code" => "KZT"),
		array("id" => 113, "code" => "KE", "name" => "Kenya", "phonecode" => 254, "currency_name" => "Kenyan shilling", "currency_symbol" => "", "currency_code" => "KES"),
		array("id" => 114, "code" => "KI", "name" => "Kiribati", "phonecode" => 686, "currency_name" => "Australian dollar", "currency_symbol" => "", "currency_code" => "AUD"),
		array("id" => 115, "code" => "KP", "name" => "Korea North", "phonecode" => 850, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 116, "code" => "KR", "name" => "Korea South", "phonecode" => 82, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 117, "code" => "KW", "name" => "Kuwait", "phonecode" => 965, "currency_name" => "Kuwaiti dinar", "currency_symbol" => "", "currency_code" => "KWD"),
		array("id" => 118, "code" => "KG", "name" => "Kyrgyzstan", "phonecode" => 996, "currency_name" => "Kyrgyzstani som", "currency_symbol" => "", "currency_code" => "KGS"),
		array("id" => 119, "code" => "LA", "name" => "Laos", "phonecode" => 856, "currency_name" => "Lao kip", "currency_symbol" => "", "currency_code" => "LAK"),
		array("id" => 120, "code" => "LV", "name" => "Latvia", "phonecode" => 371, "currency_name" => "Euro", "currency_symbol" => "", "currency_code" => "EUR"),
		array("id" => 121, "code" => "LB", "name" => "Lebanon", "phonecode" => 961, "currency_name" => "Lebanese pound", "currency_symbol" => "", "currency_code" => "LBP"),
		array("id" => 122, "code" => "LS", "name" => "Lesotho", "phonecode" => 266, "currency_name" => "Lesotho loti", "currency_symbol" => "", "currency_code" => "LSL"),
		array("id" => 123, "code" => "LR", "name" => "Liberia", "phonecode" => 231, "currency_name" => "Liberian dollar", "currency_symbol" => "", "currency_code" => "LRD"),
		array("id" => 124, "code" => "LY", "name" => "Libya", "phonecode" => 218, "currency_name" => "Libyan dinar", "currency_symbol" => "", "currency_code" => "LYD"),
		array("id" => 125, "code" => "LI", "name" => "Liechtenstein", "phonecode" => 423, "currency_name" => "Swiss franc", "currency_symbol" => "", "currency_code" => "CHF"),
		array("id" => 126, "code" => "LT", "name" => "Lithuania", "phonecode" => 370, "currency_name" => "Euro", "currency_symbol" => "", "currency_code" => "EUR"),
		array("id" => 127, "code" => "LU", "name" => "Luxembourg", "phonecode" => 352, "currency_name" => "Euro", "currency_symbol" => "", "currency_code" => "EUR"),
		array("id" => 128, "code" => "MO", "name" => "Macau S.A.R.", "phonecode" => 853, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 129, "code" => "MK", "name" => "Macedonia", "phonecode" => 389, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 130, "code" => "MG", "name" => "Madagascar", "phonecode" => 261, "currency_name" => "Malagasy ariary", "currency_symbol" => "", "currency_code" => "MGA"),
		array("id" => 131, "code" => "MW", "name" => "Malawi", "phonecode" => 265, "currency_name" => "Malawian kwacha", "currency_symbol" => "", "currency_code" => "MWK"),
		array("id" => 132, "code" => "MY", "name" => "Malaysia", "phonecode" => 60, "currency_name" => "Malaysian ringgit", "currency_symbol" => "", "currency_code" => "MYR"),
		array("id" => 133, "code" => "MV", "name" => "Maldives", "phonecode" => 960, "currency_name" => "Maldivian rufiyaa", "currency_symbol" => "", "currency_code" => "MVR"),
		array("id" => 134, "code" => "ML", "name" => "Mali", "phonecode" => 223, "currency_name" => "West African CFA fra", "currency_symbol" => "", "currency_code" => "XOF"),
		array("id" => 135, "code" => "MT", "name" => "Malta", "phonecode" => 356, "currency_name" => "Euro", "currency_symbol" => "", "currency_code" => "EUR"),
		array("id" => 136, "code" => "XM", "name" => "Man (Isle of)", "phonecode" => 44, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 137, "code" => "MH", "name" => "Marshall Islands", "phonecode" => 692, "currency_name" => "United States dollar", "currency_symbol" => "", "currency_code" => "USD"),
		array("id" => 138, "code" => "MQ", "name" => "Martinique", "phonecode" => 596, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 139, "code" => "MR", "name" => "Mauritania", "phonecode" => 222, "currency_name" => "Mauritanian ouguiya", "currency_symbol" => "", "currency_code" => "MRO"),
		array("id" => 140, "code" => "MU", "name" => "Mauritius", "phonecode" => 230, "currency_name" => "Mauritian rupee", "currency_symbol" => "", "currency_code" => "MUR"),
		array("id" => 141, "code" => "YT", "name" => "Mayotte", "phonecode" => 269, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 142, "code" => "MX", "name" => "Mexico", "phonecode" => 52, "currency_name" => "Mexican peso", "currency_symbol" => "", "currency_code" => "MXN"),
		array("id" => 143, "code" => "FM", "name" => "Micronesia", "phonecode" => 691, "currency_name" => "Micronesian dollar", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 144, "code" => "MD", "name" => "Moldova", "phonecode" => 373, "currency_name" => "Moldovan leu", "currency_symbol" => "", "currency_code" => "MDL"),
		array("id" => 145, "code" => "MC", "name" => "Monaco", "phonecode" => 377, "currency_name" => "Euro", "currency_symbol" => "", "currency_code" => "EUR"),
		array("id" => 146, "code" => "MN", "name" => "Mongolia", "phonecode" => 976, "currency_name" => "Mongolian tögrög", "currency_symbol" => "", "currency_code" => "MNT"),
		array("id" => 147, "code" => "MS", "name" => "Montserrat", "phonecode" => 1664, "currency_name" => "East Caribbean dolla", "currency_symbol" => "", "currency_code" => "XCD"),
		array("id" => 148, "code" => "MA", "name" => "Morocco", "phonecode" => 212, "currency_name" => "Moroccan dirham", "currency_symbol" => "", "currency_code" => "MAD"),
		array("id" => 149, "code" => "MZ", "name" => "Mozambique", "phonecode" => 258, "currency_name" => "Mozambican metical", "currency_symbol" => "", "currency_code" => "MZN"),
		array("id" => 150, "code" => "MM", "name" => "Myanmar", "phonecode" => 95, "currency_name" => "Burmese kyat", "currency_symbol" => "", "currency_code" => "MMK"),
		array("id" => 151, "code" => "NA", "name" => "Namibia", "phonecode" => 264, "currency_name" => "Namibian dollar", "currency_symbol" => "", "currency_code" => "NAD"),
		array("id" => 152, "code" => "NR", "name" => "Nauru", "phonecode" => 674, "currency_name" => "Australian dollar", "currency_symbol" => "", "currency_code" => "AUD"),
		array("id" => 153, "code" => "NP", "name" => "Nepal", "phonecode" => 977, "currency_name" => "Nepalese rupee", "currency_symbol" => "", "currency_code" => "NPR"),
		array("id" => 154, "code" => "AN", "name" => "Netherlands Antilles", "phonecode" => 599, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 155, "code" => "NL", "name" => "Netherlands The", "phonecode" => 31, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 156, "code" => "NC", "name" => "New Caledonia", "phonecode" => 687, "currency_name" => "CFP franc", "currency_symbol" => "", "currency_code" => "XPF"),
		array("id" => 157, "code" => "NZ", "name" => "New Zealand", "phonecode" => 64, "currency_name" => "New Zealand dollar", "currency_symbol" => "", "currency_code" => "NZD"),
		array("id" => 158, "code" => "NI", "name" => "Nicaragua", "phonecode" => 505, "currency_name" => "Nicaraguan córdoba", "currency_symbol" => "", "currency_code" => "NIO"),
		array("id" => 159, "code" => "NE", "name" => "Niger", "phonecode" => 227, "currency_name" => "West African CFA fra", "currency_symbol" => "", "currency_code" => "XOF"),
		array("id" => 160, "code" => "NG", "name" => "Nigeria", "phonecode" => 234, "currency_name" => "Nigerian naira", "currency_symbol" => "", "currency_code" => "NGN"),
		array("id" => 161, "code" => "NU", "name" => "Niue", "phonecode" => 683, "currency_name" => "New Zealand dollar", "currency_symbol" => "", "currency_code" => "NZD"),
		array("id" => 162, "code" => "NF", "name" => "Norfolk Island", "phonecode" => 672, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 163, "code" => "MP", "name" => "Northern Mariana Islands", "phonecode" => 1670, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 164, "code" => "NO", "name" => "Norway", "phonecode" => 47, "currency_name" => "Norwegian krone", "currency_symbol" => "", "currency_code" => "NOK"),
		array("id" => 165, "code" => "OM", "name" => "Oman", "phonecode" => 968, "currency_name" => "Omani rial", "currency_symbol" => "", "currency_code" => "OMR"),
		array("id" => 166, "code" => "PK", "name" => "Pakistan", "phonecode" => 92, "currency_name" => "Pakistani rupee", "currency_symbol" => "", "currency_code" => "PKR"),
		array("id" => 167, "code" => "PW", "name" => "Palau", "phonecode" => 680, "currency_name" => "Palauan dollar", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 168, "code" => "PS", "name" => "Palestinian Territory Occupied", "phonecode" => 970, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 169, "code" => "PA", "name" => "Panama", "phonecode" => 507, "currency_name" => "Panamanian balboa", "currency_symbol" => "", "currency_code" => "PAB"),
		array("id" => 170, "code" => "PG", "name" => "Papua new Guinea", "phonecode" => 675, "currency_name" => "Papua New Guinean ki", "currency_symbol" => "", "currency_code" => "PGK"),
		array("id" => 171, "code" => "PY", "name" => "Paraguay", "phonecode" => 595, "currency_name" => "Paraguayan guaraní", "currency_symbol" => "", "currency_code" => "PYG"),
		array("id" => 172, "code" => "PE", "name" => "Peru", "phonecode" => 51, "currency_name" => "Peruvian nuevo sol", "currency_symbol" => "", "currency_code" => "PEN"),
		array("id" => 173, "code" => "PH", "name" => "Philippines", "phonecode" => 63, "currency_name" => "Philippine peso", "currency_symbol" => "", "currency_code" => "PHP"),
		array("id" => 174, "code" => "PN", "name" => "Pitcairn Island", "phonecode" => 0, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 175, "code" => "PL", "name" => "Poland", "phonecode" => 48, "currency_name" => "Polish złoty", "currency_symbol" => "", "currency_code" => "PLN"),
		array("id" => 176, "code" => "PT", "name" => "Portugal", "phonecode" => 351, "currency_name" => "Euro", "currency_symbol" => "", "currency_code" => "EUR"),
		array("id" => 177, "code" => "PR", "name" => "Puerto Rico", "phonecode" => 1787, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 178, "code" => "QA", "name" => "Qatar", "phonecode" => 974, "currency_name" => "Qatari riyal", "currency_symbol" => "", "currency_code" => "QAR"),
		array("id" => 179, "code" => "RE", "name" => "Reunion", "phonecode" => 262, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 180, "code" => "RO", "name" => "Romania", "phonecode" => 40, "currency_name" => "Romanian leu", "currency_symbol" => "", "currency_code" => "RON"),
		array("id" => 181, "code" => "RU", "name" => "Russia", "phonecode" => 70, "currency_name" => "Russian ruble", "currency_symbol" => "", "currency_code" => "RUB"),
		array("id" => 182, "code" => "RW", "name" => "Rwanda", "phonecode" => 250, "currency_name" => "Rwandan franc", "currency_symbol" => "", "currency_code" => "RWF"),
		array("id" => 183, "code" => "SH", "name" => "Saint Helena", "phonecode" => 290, "currency_name" => "Saint Helena pound", "currency_symbol" => "", "currency_code" => "SHP"),
		array("id" => 184, "code" => "KN", "name" => "Saint Kitts And Nevis", "phonecode" => 1869, "currency_name" => "East Caribbean dolla", "currency_symbol" => "", "currency_code" => "XCD"),
		array("id" => 185, "code" => "LC", "name" => "Saint Lucia", "phonecode" => 1758, "currency_name" => "East Caribbean dolla", "currency_symbol" => "", "currency_code" => "XCD"),
		array("id" => 186, "code" => "PM", "name" => "Saint Pierre and Miquelon", "phonecode" => 508, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 187, "code" => "VC", "name" => "Saint Vincent And The Grenadines", "phonecode" => 1784, "currency_name" => "East Caribbean dolla", "currency_symbol" => "", "currency_code" => "XCD"),
		array("id" => 188, "code" => "WS", "name" => "Samoa", "phonecode" => 684, "currency_name" => "Samoan tālā", "currency_symbol" => "", "currency_code" => "WST"),
		array("id" => 189, "code" => "SM", "name" => "San Marino", "phonecode" => 378, "currency_name" => "Euro", "currency_symbol" => "", "currency_code" => "EUR"),
		array("id" => 190, "code" => "ST", "name" => "Sao Tome and Principe", "phonecode" => 239, "currency_name" => "São Tomé and Prín", "currency_symbol" => "", "currency_code" => "STD"),
		array("id" => 191, "code" => "SA", "name" => "Saudi Arabia", "phonecode" => 966, "currency_name" => "Saudi riyal", "currency_symbol" => "", "currency_code" => "SAR"),
		array("id" => 192, "code" => "SN", "name" => "Senegal", "phonecode" => 221, "currency_name" => "West African CFA fra", "currency_symbol" => "", "currency_code" => "XOF"),
		array("id" => 193, "code" => "RS", "name" => "Serbia", "phonecode" => 381, "currency_name" => "Serbian dinar", "currency_symbol" => "", "currency_code" => "RSD"),
		array("id" => 194, "code" => "SC", "name" => "Seychelles", "phonecode" => 248, "currency_name" => "Seychellois rupee", "currency_symbol" => "", "currency_code" => "SCR"),
		array("id" => 195, "code" => "SL", "name" => "Sierra Leone", "phonecode" => 232, "currency_name" => "Sierra Leonean leone", "currency_symbol" => "", "currency_code" => "SLL"),
		array("id" => 196, "code" => "SG", "name" => "Singapore", "phonecode" => 65, "currency_name" => "Brunei dollar", "currency_symbol" => "", "currency_code" => "BND"),
		array("id" => 197, "code" => "SK", "name" => "Slovakia", "phonecode" => 421, "currency_name" => "Euro", "currency_symbol" => "", "currency_code" => "EUR"),
		array("id" => 198, "code" => "SI", "name" => "Slovenia", "phonecode" => 386, "currency_name" => "Euro", "currency_symbol" => "", "currency_code" => "EUR"),
		array("id" => 199, "code" => "XG", "name" => "Smaller Territories of the UK", "phonecode" => 44, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 200, "code" => "SB", "name" => "Solomon Islands", "phonecode" => 677, "currency_name" => "Solomon Islands doll", "currency_symbol" => "", "currency_code" => "SBD"),
		array("id" => 201, "code" => "SO", "name" => "Somalia", "phonecode" => 252, "currency_name" => "Somali shilling", "currency_symbol" => "", "currency_code" => "SOS"),
		array("id" => 202, "code" => "ZA", "name" => "South Africa", "phonecode" => 27, "currency_name" => "South African rand", "currency_symbol" => "", "currency_code" => "ZAR"),
		array("id" => 203, "code" => "GS", "name" => "South Georgia", "phonecode" => 0, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 204, "code" => "SS", "name" => "South Sudan", "phonecode" => 211, "currency_name" => "South Sudanese pound", "currency_symbol" => "", "currency_code" => "SSP"),
		array("id" => 205, "code" => "ES", "name" => "Spain", "phonecode" => 34, "currency_name" => "Euro", "currency_symbol" => "", "currency_code" => "EUR"),
		array("id" => 206, "code" => "LK", "name" => "Sri Lanka", "phonecode" => 94, "currency_name" => "Sri Lankan rupee", "currency_symbol" => "", "currency_code" => "LKR"),
		array("id" => 207, "code" => "SD", "name" => "Sudan", "phonecode" => 249, "currency_name" => "Sudanese pound", "currency_symbol" => "", "currency_code" => "SDG"),
		array("id" => 208, "code" => "SR", "name" => "Suriname", "phonecode" => 597, "currency_name" => "Surinamese dollar", "currency_symbol" => "", "currency_code" => "SRD"),
		array("id" => 209, "code" => "SJ", "name" => "Svalbard And Jan Mayen Islands", "phonecode" => 47, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 210, "code" => "SZ", "name" => "Swaziland", "phonecode" => 268, "currency_name" => "Swazi lilangeni", "currency_symbol" => "", "currency_code" => "SZL"),
		array("id" => 211, "code" => "SE", "name" => "Sweden", "phonecode" => 46, "currency_name" => "Swedish krona", "currency_symbol" => "", "currency_code" => "SEK"),
		array("id" => 212, "code" => "CH", "name" => "Switzerland", "phonecode" => 41, "currency_name" => "Swiss franc", "currency_symbol" => "", "currency_code" => "CHF"),
		array("id" => 213, "code" => "SY", "name" => "Syria", "phonecode" => 963, "currency_name" => "Syrian pound", "currency_symbol" => "", "currency_code" => "SYP"),
		array("id" => 214, "code" => "TW", "name" => "Taiwan", "phonecode" => 886, "currency_name" => "New Taiwan dollar", "currency_symbol" => "", "currency_code" => "TWD"),
		array("id" => 215, "code" => "TJ", "name" => "Tajikistan", "phonecode" => 992, "currency_name" => "Tajikistani somoni", "currency_symbol" => "", "currency_code" => "TJS"),
		array("id" => 216, "code" => "TZ", "name" => "Tanzania", "phonecode" => 255, "currency_name" => "Tanzanian shilling", "currency_symbol" => "", "currency_code" => "TZS"),
		array("id" => 217, "code" => "TH", "name" => "Thailand", "phonecode" => 66, "currency_name" => "Thai baht", "currency_symbol" => "", "currency_code" => "THB"),
		array("id" => 218, "code" => "TG", "name" => "Togo", "phonecode" => 228, "currency_name" => "West African CFA fra", "currency_symbol" => "", "currency_code" => "XOF"),
		array("id" => 219, "code" => "TK", "name" => "Tokelau", "phonecode" => 690, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 220, "code" => "TO", "name" => "Tonga", "phonecode" => 676, "currency_name" => "Tongan paʻanga", "currency_symbol" => "", "currency_code" => "TOP"),
		array("id" => 221, "code" => "TT", "name" => "Trinidad And Tobago", "phonecode" => 1868, "currency_name" => "Trinidad and Tobago ", "currency_symbol" => "", "currency_code" => "TTD"),
		array("id" => 222, "code" => "TN", "name" => "Tunisia", "phonecode" => 216, "currency_name" => "Tunisian dinar", "currency_symbol" => "", "currency_code" => "TND"),
		array("id" => 223, "code" => "TR", "name" => "Turkey", "phonecode" => 90, "currency_name" => "Turkish lira", "currency_symbol" => "", "currency_code" => "TRY"),
		array("id" => 224, "code" => "TM", "name" => "Turkmenistan", "phonecode" => 7370, "currency_name" => "Turkmenistan manat", "currency_symbol" => "", "currency_code" => "TMT"),
		array("id" => 225, "code" => "TC", "name" => "Turks And Caicos Islands", "phonecode" => 1649, "currency_name" => "United States dollar", "currency_symbol" => "", "currency_code" => "USD"),
		array("id" => 226, "code" => "TV", "name" => "Tuvalu", "phonecode" => 688, "currency_name" => "Australian dollar", "currency_symbol" => "", "currency_code" => "AUD"),
		array("id" => 227, "code" => "UG", "name" => "Uganda", "phonecode" => 256, "currency_name" => "Ugandan shilling", "currency_symbol" => "", "currency_code" => "UGX"),
		array("id" => 228, "code" => "UA", "name" => "Ukraine", "phonecode" => 380, "currency_name" => "Ukrainian hryvnia", "currency_symbol" => "", "currency_code" => "UAH"),
		array("id" => 229, "code" => "AE", "name" => "United Arab Emirates", "phonecode" => 971, "currency_name" => "United Arab Emirates", "currency_symbol" => "د.إ", "currency_code" => "AED"),
		array("id" => 230, "code" => "GB", "name" => "United Kingdom", "phonecode" => 44, "currency_name" => "British pound", "currency_symbol" => "£", "currency_code" => "GBP"),
		array("id" => 231, "code" => "US", "name" => "United States", "phonecode" => 1, "currency_name" => "United States dollar", "currency_symbol" => "", "currency_code" => "USD"),
		array("id" => 232, "code" => "UM", "name" => "United States Minor Outlying Islands", "phonecode" => 1, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 233, "code" => "UY", "name" => "Uruguay", "phonecode" => 598, "currency_name" => "Uruguayan peso", "currency_symbol" => "", "currency_code" => "UYU"),
		array("id" => 234, "code" => "UZ", "name" => "Uzbekistan", "phonecode" => 998, "currency_name" => "Uzbekistani som", "currency_symbol" => "", "currency_code" => "UZS"),
		array("id" => 235, "code" => "VU", "name" => "Vanuatu", "phonecode" => 678, "currency_name" => "Vanuatu vatu", "currency_symbol" => "", "currency_code" => "VUV"),
		array("id" => 236, "code" => "VA", "name" => "Vatican City State (Holy See)", "phonecode" => 39, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 237, "code" => "VE", "name" => "Venezuela", "phonecode" => 58, "currency_name" => "Venezuelan bolívar", "currency_symbol" => "", "currency_code" => "VEF"),
		array("id" => 238, "code" => "VN", "name" => "Vietnam", "phonecode" => 84, "currency_name" => "Vietnamese đồng", "currency_symbol" => "", "currency_code" => "VND"),
		array("id" => 239, "code" => "VG", "name" => "Virgin Islands (British)", "phonecode" => 1284, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 240, "code" => "VI", "name" => "Virgin Islands (US)", "phonecode" => 1340, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 241, "code" => "WF", "name" => "Wallis And Futuna Islands", "phonecode" => 681, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 242, "code" => "EH", "name" => "Western Sahara", "phonecode" => 212, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 243, "code" => "YE", "name" => "Yemen", "phonecode" => 967, "currency_name" => "Yemeni rial", "currency_symbol" => "", "currency_code" => "YER"),
		array("id" => 244, "code" => "YU", "name" => "Yugoslavia", "phonecode" => 38, "currency_name" => "", "currency_symbol" => "", "currency_code" => ""),
		array("id" => 245, "code" => "ZM", "name" => "Zambia", "phonecode" => 260, "currency_name" => "Zambian kwacha", "currency_symbol" => "", "currency_code" => "ZMW"),
		array("id" => 246, "code" => "ZW", "name" => "Zimbabwe", "phonecode" => 263, "currency_name" => "Botswana pula", "currency_symbol" => "", "currency_code" => "BWP"),
		);
		DB::table('countries')->insert($countries);
    }
}
